#! /bin/sh

### BEGIN INIT INFO
# Provides:          iptables
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Descr/sbin/iptablesion: starts iptables
# Descr/sbin/iptablesion:       Starts IPTABLES
### END INIT INFO

. /lib/lsb/init-functions

start ()
{
	        echo "starting"

ip6tables -P INPUT  DROP
ip6tables -P OUTPUT  ACCEPT
ip6tables -P FORWARD  DROP

/sbin/iptables -P INPUT DROP
/sbin/iptables -P FORWARD DROP
/sbin/iptables -P OUTPUT ACCEPT

/sbin/iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT 
/sbin/iptables -A INPUT -i lo -j ACCEPT 
/sbin/iptables -A INPUT -p icmp -j ACCEPT
/sbin/iptables -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT 
/sbin/iptables -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
/sbin/iptables -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
/sbin/iptables -A INPUT -m limit --limit 1/min -j LOG --log-prefix "IPTables-IN-Dropped: " 

#/sbin/iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT 
#/sbin/iptables -A OUTPUT -o lo -j ACCEPT 
#/sbin/iptables -A OUTPUT -p tcp -m tcp --sport 80 -j ACCEPT 
#/sbin/iptables -A OUTPUT -p tcp -m tcp --dport 22 -j ACCEPT 
#/sbin/iptables -A OUTPUT -p tcp -m tcp --sport 443 -j ACCEPT 
#/sbin/iptables -A OUTPUT -m limit --limit 2/min -j LOG --log-prefix "IPTables-OUT-Dropped: " 

#/etc/init.d/fail2ban restart

}

stop()
{
        echo "stopping"
    for a in `cat /proc/net/ip_tables_names`; do
            /sbin/iptables -F -t $a
            /sbin/iptables -X -t $a
                done
                /sbin/iptables -t nat -P PREROUTING ACCEPT
                /sbin/iptables -t nat -P POSTROUTING ACCEPT
                /sbin/iptables -t nat -P OUTPUT ACCEPT
                /sbin/iptables -t mangle -P PREROUTING ACCEPT
                /sbin/iptables -t mangle -P INPUT ACCEPT
                /sbin/iptables -t mangle -P FORWARD ACCEPT
                /sbin/iptables -t mangle -P OUTPUT ACCEPT
                /sbin/iptables -t mangle -P POSTROUTING ACCEPT
                /sbin/iptables -t filter -P INPUT ACCEPT
                /sbin/iptables -t filter -P FORWARD ACCEPT
                /sbin/iptables -t filter -P OUTPUT ACCEPT

}


case "$1" in

    start)
        log_begin_msg "Starting firewall..."
        start
#        service fail2ban restart
        log_end_msg $?
    ;;

    stop)
        log_begin_msg "Stopping firewall..."
        stop
#        service fail2ban restart
        log_end_msg 0
    ;;

    restart)
        log_begin_msg "Restarting firewall..."
        stop
        start
        log_end_msg $?
    ;;

        *)
                echo "Usage: /etc/init.d/iptables {start|stop|restart}" >&2
                exit 1
        ;;
esac

exit 0
